export const SET_SCALE = 'SET_SCALE'
export type SET_SCALE = typeof SET_SCALE

export const INCREASE_SCALE = 'INCREASE_SCALE'
export type INCREASE_SCALE = typeof INCREASE_SCALE

export const DECREASE_SCALE = 'DECREASE_SCALE'
export type DECREASE_SCALE = typeof DECREASE_SCALE

export const SET_DIAGRAM_TYPE = 'SET_DIAGRAM_TYPE'
export type SET_DIAGRAM_TYPE = typeof SET_DIAGRAM_TYPE

export const SET_XOFFSET = 'SET_XOFFSET'
export type SET_XOFFSET = typeof SET_XOFFSET

export const SET_YOFFSET = 'SET_YOFFSET'
export type SET_YOFFSET = typeof SET_YOFFSET

export const ADD_ENTITY = 'ADD_ENTITY'
export type ADD_ENTITY = typeof ADD_ENTITY

export const REMOVE_ENTITY = 'REMOVE_ENTITY'
export type REMOVE_ENTITY = typeof REMOVE_ENTITY

export const UPDATE_ENTITY = 'UPDATE_ENTITY'
export type UPDATE_ENTITY = typeof UPDATE_ENTITY

export const ADD_CONNECTION = 'ADD_CONNECTION'
export type ADD_CONNECTION = typeof ADD_CONNECTION

export const REMOVE_CONNECTION = 'REMOVE_CONNECTION'
export type REMOVE_CONNECTION = typeof REMOVE_CONNECTION

export const UPDATE_CONNECTION = 'UPDATE_CONNECTION'
export type UPDATE_CONNECTION = typeof UPDATE_CONNECTION

export const SET_MOUSE_MODE = 'SET_MOUSE_MODE'
export type SET_MOUSE_MODE = typeof SET_MOUSE_MODE

export const SET_CURRENT_DIAGRAM_CONNECTION = 'SET_CURRENT_CONNECTION'
export type SET_CURRENT_DIAGRAM_CONNECTION = typeof SET_CURRENT_DIAGRAM_CONNECTION

export const SET_ENTITY_TYPE_CHOOSER_STATE = 'SET_ENTITY_TYPE_CHOOSER_STATE'
export type SET_ENTITY_TYPE_CHOOSER_STATE = typeof SET_ENTITY_TYPE_CHOOSER_STATE

export const SET_CONNECTION_TYPE_CHOOSER_STATE = 'SET_CONNECTION_TYPE_CHOOSER_STATE'
export type SET_CONNECTION_TYPE_CHOOSER_STATE = typeof SET_CONNECTION_TYPE_CHOOSER_STATE

export const SET_SAVE_PANEL_IS_OPEN = 'SET_SAVE_PANEL_IS_OPEN'
export type SET_SAVE_PANEL_IS_OPEN = typeof SET_SAVE_PANEL_IS_OPEN

export const SET_LAST_SAVE_SETTINGS = 'SET_LAST_SAVE_SETTINGS'
export type SET_LAST_SAVE_SETTINGS = typeof SET_LAST_SAVE_SETTINGS

export const SET_IS_SAVING = 'SET_IS_SAVING'
export type SET_IS_SAVING = typeof SET_IS_SAVING

export const SET_TUTORIAL_IS_OPEN = 'SET_TUTORIAL_IS_OPEN'
export type SET_TUTORIAL_IS_OPEN = typeof SET_TUTORIAL_IS_OPEN